name: Build, Test, and Push Docker Container
on:
  push:
    branches:
      - docker_ci
jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Fetch dev branch to get train.py
        run: git fetch --all
      - name: Checkout train.py from dev branch
        run: git checkout origin/dev -- train.py
      - name: Run train.py to generate the model file
        run: python train.py
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-pipeline-assignment-3:latest
      - name: Run Docker container for verification
        run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/mlops-pipeline-assignment-3:latest
      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-pipeline-assignment-3:latest